import './globals.css'
import { Inter, Oswald } from 'next/font/google'

const oswald = Oswald({ subsets: ['latin'] })

export const metadata = {
  title: 'ProjectCon',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={oswald.className}>{children}</body>
    </html>
  )
}